In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('C:\\Users\\Abdullah\\Desktop\\Code\\Sentiment Based Stock\\Sentiment Based Stocks\\data\\bitcoin_us_treasury.csv')

In [4]:
df.head()

,Unnamed: 0,timestamp,open,high,low,close,volume,datetime_utc,merge_date,domestic_series,...,total_non-marketable,treasury_bills,treasury_bonds,treasury_floating_rate_notes_(frn),treasury_inflation-protected_securities_(tips),treasury_notes,united_states_savings_inflation_securities,united_states_savings_securities,weighted_sentiment,sentiment_missing
0,0,1669852800000,17165.44,17317.80,16855.00,16980.08,31798.991518,2022-12-01 00:00:00+00:00,2022-12-01,7.577,...,2.135,3.456,3.012,4.104,0.487,1.68,10.148,2.694,0.408548,0
1,1,1669939200000,16980.07,17108.25,16791.02,17094.71,23096.436867,2022-12-02 00:00:00+00:00,2022-12-02,7.577,...,2.135,3.456,3.012,4.104,0.487,1.68,10.148,2.694,0.136171,0
2,2,1670025600000,17094.25,17158.42,16863.58,16888.53,14081.450672,2022-12-03 00:00:00+00:00,2022-12-03,7.577,...,2.135,3.456,3.012,4.104,0.487,1.68,10.148,2.694,-0.347766,0
3,3,1670112000000,16889.17,17199.99,16882.86,17108.90,16961.108288,2022-12-04 00:00:00+00:00,2022-12-04,7.577,...,2.135,3.456,3.012,4.104,0.487,1.68,10.148,2.694,0.502235,0
4,4,1670198400000,17108.90,17424.59,16865.22,16966.05,33618.451090,2022-12-05 00:00:00+00:00,2022-12-05,7.577,...,2.135,3.456,3.012,4.104,0.487,1.68,10.148,2.694,0.326272,0

In [5]:
print(df.columns.to_list())

['Unnamed: 0', 'timestamp', 'open', 'high', 'low', 'close', 'volume', 'datetime_utc', 'merge_date', 'domestic_series', 'federal_financing_bank', 'foreign_series', 'government_account_series', 'government_account_series_inflation_securities', 'special_purpose_vehicle', 'state_and_local_government_series', 'total_interest-bearing_debt', 'total_marketable', 'total_non-marketable', 'treasury_bills', 'treasury_bonds', 'treasury_floating_rate_notes_(frn)', 'treasury_inflation-protected_securities_(tips)', 'treasury_notes', 'united_states_savings_inflation_securities', 'united_states_savings_securities', 'weighted_sentiment', 'sentiment_missing']

In [6]:
cols = ['open', 'low', 'high', 'close', 'volume', 'weighted_sentiment']

In [7]:
df = df[cols]

In [8]:
df.head()

       open       low      high     close        volume  weighted_sentiment
0  17165.44  16855.00  17317.80  16980.08  31798.991518            0.408548
1  16980.07  16791.02  17108.25  17094.71  23096.436867            0.136171
2  17094.25  16863.58  17158.42  16888.53  14081.450672           -0.347766
3  16889.17  16882.86  17199.99  17108.90  16961.108288            0.502235
4  17108.90  16865.22  17424.59  16966.05  33618.451090            0.326272

In [9]:
df.shape

(1074, 6)

In [10]:
df.describe()

,open,low,high,close,volume,weighted_sentiment
count,1074.000000,1074.000000,1074.000000,1074.000000,1074.000000,1074.000000
mean,62766.576369,61635.193082,63895.587095,62845.825503,12289.885502,0.347973
std,32594.465568,32046.111364,33072.661437,32586.775886,9041.471112,0.274657
min,16439.980000,16273.400000,16621.000000,16439.740000,1227.768033,-0.749771
25%,29289.320000,29046.145000,29707.272500,29321.770000,5852.254197,0.171151
50%,62104.570000,60661.695000,63420.420000,62161.150000,10378.102054,0.376796
75%,95116.980000,93633.902500,96842.500000,95488.255000,15975.870276,0.540075
max,124723.570000,123115.770000,126296.000000,124720.090000,65575.095373,0.952912

In [11]:
df['returns'] = df['close'].pct_change()

In [12]:
df['volatility'] = df['returns'].rolling(window=24).std()

In [13]:
def calculate_rsi(data, window=14):
    delta = data.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=window).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=window).mean()
    rs = gain / loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

df['rsi'] = calculate_rsi(df['close'])

In [14]:
df['ma_7']  = df['close'].rolling(7).mean()
df['ma_30'] = df['close'].rolling(30).mean()

In [15]:
df.dropna(inplace=True)

In [16]:
df.head()

,open,low,high,close,volume,weighted_sentiment,returns,volatility,rsi,ma_7,ma_30
29,16627.36,16326.16,16649.99,16600.10,26532.280034,0.354333,-0.001650,0.015861,49.054641,16721.447143,16954.928333
30,16599.98,16462.49,16634.42,16530.35,15414.529404,-0.212205,-0.004202,0.015617,42.325644,16677.622857,16939.937333
31,16531.83,16490.00,16621.00,16611.58,10668.736977,-0.220899,0.004914,0.014848,46.146480,16646.560000,16923.833000
32,16611.90,16542.52,16789.99,16666.95,13560.460180,0.673105,0.003333,0.014851,57.915235,16610.701429,16916.447000
33,16666.86,16600.00,16772.30,16669.47,17612.355277,0.184808,0.000151,0.014852,38.356738,16606.521429,16901.799333

In [17]:
df['regime'] = (df['volatility'] > df['volatility'].median()).astype(int)
df.to_csv('btc_features.csv', index=False)